---
kubectl_ver: v1.13.4
kubectl_platform: amd64
kubectl_mirror: https://storage.googleapis.com/kubernetes-release/release

kubectl_checksums:
  v1.8.2:
    darwin:
      amd64: sha256:6b2ec18341b7e4b86c05d512001e44f76f557dbe9eadf773c225ca48260d9bc4
    linux:
      amd64: sha256:c5c258b0728d9c0806b34079e130f21f304439c9a824d46ce3d62ad4dbeeb0d0
      arm64: sha256:e3a813a3fd4d9dc40c2b082c411be4440355bef284b1172cada15e01a197f6a1
  v1.8.4:
    darwin:
      amd64: sha256:be37c5d162d781ec1ede85b89db5b1c31a1b40246767723acf688222c903e64d
    linux:
      amd64: sha256:fb3cbf25e71f414381e8a6b8a2dc2abb19344feea660ac0445ccf5d43a093f10
      arm64: sha256:bc20eb719972a033c9decef71ece436061a4d3e6e744ae3d9c47014ded65a555
  v1.8.5:
    darwin:
      amd64: sha256:5684b0b4bc4bc2e75e48f0325988dc7798963851c554f9e6affbf65e20c57f43
    linux:
      amd64: sha256:2663511441d44b844a25925b7d74d9326d86b8347408d21ed6efbd27a7f7109a
      arm64: sha256:384acac1e0ac64e853c06fb538baf390cbf30e06f43c6871031d425dac532658
  v1.9.1:
    darwin:
      amd64: sha256:2121f7b573aac3835dbd1994ad4f6028eca979de2dc8dfa27e39d34b96288337
    linux:
      amd64: sha256:ec1abbc1b91fb23e00558c09892d053012c7581afe6e5a36cada3713b0b7c37b
      arm64: sha256:44c93cd2fb3eb72945ad1cf6b6fe3f5251fe77cd54e4e3d76c4bfc50ff7dc36b
  v1.9.2:
    darwin:
      amd64: sha256:0114255568a8b5cb998c516370f3822bebe78b84d1e914d4d9afff95518a56c0
    linux:
      amd64: sha256:455999c8232c57748f4cee4b5446ee39fe8af093434d732ddcd628a02f3d9118
      arm64: sha256:37dcd4d26510454407d461b7fa54831ee39255697ceaea8f3d6d7e0c0d9724da
  v1.9.3:
    darwin:
      amd64: sha256:a7e41b1e28f45be6bbbe90bdce011dee82baddbd6788327bcd0dac93b87f0a46
    linux:
      amd64: sha256:81eb30e62a12d6e0527a6a3c2a9501b56d65777bf66684739b16a0afe826c8f8
      arm64: sha256:0bdfe145a192c547b508a61fdd8e4dc165b12c85d5ffad5ed04736d2834cccc4
  v1.9.4:
    darwin:
      amd64: sha256:47af315aaaba78408f3351673ad5a310debaa4090bd5c6e45e4f210c428fb6bc
    linux:
      amd64: sha256:1649bcda95e1662da0616a5314261285fa4154d769dc4148cc339d859b564c39
      arm64: sha256:64a79bcfc515259d6e05fd4f9bc4a24557dbbb6bd88129bbd4fbc02417aa4304
  v1.9.5:
    darwin:
      amd64: sha256:7cea63e41db83eb772d4fb02e3804fc8b7f541af1d1b774d4e715df320f3954c
    linux:
      amd64: sha256:9c67b6e80e9dd3880511c7d912c5a01399c1d74aaf4d71989c7d5a4f2534bcd5
      arm64: sha256:6335a5ac2e4e14c3aedbcecd9d112c8ae13346f6355201682eb3a3b4525bfaf7
  v1.9.6:
    darwin:
      amd64: sha256:827d49289418677b44245681bc64dcc0469882f903d6a0d29a04cf3b035207e6
    linux:
      amd64: sha256:e6aa618d682d0bcc90602cbf2e22a134d36af7199d7081015042eca02ba36368
      arm64: sha256:b7a91f3d2f596e1c1a250bb2991379e39b75284c54fd194e4e1e95b845a28e46
  v1.10.0:
    darwin:
      amd64: sha256:a6a39cbfe1ebf21a71a0e8c6be90f045e4b60c76df22993a472d178fd2a3279d
    linux:
      amd64: sha256:49f7e5791d7cd91009c728eb4dc1dbf9ee1ae6a881be6b970e631116065384c3
      arm64: sha256:2b3c9f5bda3575d7636a65dd0a4783886054a02276ac75cf08129ff325441d52
  v1.10.1:
    darwin:
      amd64: sha256:9484fd8a0cba513ab91fc192f6b6659d700f411502d01a7e02acb9f3b986037c
    linux:
      amd64: sha256:1bb4d3793fb0f9e1cfee86599e0f43ae5f15578a01b61011fe7c9488e114a00b
      arm64: sha256:bf749130937b7e271b5251ace266ed246ee18576eb8e837d968d15630b500606
  v1.10.2:
    darwin:
      amd64: sha256:6373287ba463c6b036a63624b34394923527ce8cf7f018c0db93b6e2353ef2ad
    linux:
      amd64: sha256:524766fa2b88d64cff3276f4284107519f3cdd233692f08935aafa03b570f3ea
      arm64: sha256:13d3b8f254f79a624eba958f2ee29d88c01198e9bad298a9513e9d8ddb38ba19
  v1.10.3:
    darwin:
      amd64: sha256:10629291bb44e809611d4946ec1ccbb6b11602c5bffc3b11f84c4e2e80a39e58
    linux:
      amd64: sha256:62893257193f9e848f383055993e63166ab67bf872c85e896ce9b9167ba85403
      arm64: sha256:185f3cf54c3970b5ff0b938332c6753f67e089dd33c129ee3e140354eb958ea5
  v1.10.5:
    darwin:
      amd64: sha256:d67228b8e05d8129dc86a8ca23387151a0ff96c983ef49131041176ad454937e
    linux:
      amd64: sha256:a9e7f82e516aa8a652bc485620483ea964eb940787cabf890d7eab96eaac294d
      arm64: sha256:503ae52f989a9dd67b1f27d7fcff795767aa763976fbf72fe1e9f0d94828920d
  v1.11.0:
    darwin:
      amd64: sha256:caf2121289ec3013904495d6a4250d34f3feb5c97154b42a16a2258f33822efb
    linux:
      amd64: sha256:7fc84102a20aba4c766245714ce9555e3bf5d4116aab38a15b11419070a0fa90
      arm64: sha256:193b806a21694a143b7cd6e7bb6905c35eb557c849f96d608d28f69b9ee04cf3
  v1.11.1:
    darwin:
      amd64: sha256:d16ec0a4693cf4203d5e201cedf00e7a1559efaec98f54d018e67a3a17ad893d
    linux:
      amd64: sha256:d16a4e7bfe0033ea5f56f8d11e74f7a2dec5ff8832a046a643c8355b79b4ba5c
      arm64: sha256:3f91ec7cba33b9b85b5b3a99bfa33a10d7c6592c03880393ebd04d2ce6e79ac5
  v1.11.2:
    darwin:
      amd64: sha256:00982098dff8781b5837dcb15b6b1c5c8f8c3a3783ecb3f2d7300e176157e4d5
    linux:
      amd64: sha256:b9f6bf64706a0ca5f1ebb9977fc7dd155b19881985a6b116a65db5f361fbc703
      arm64: sha256:f7fe82d7076585106069424003153e0074ef1f4031d3e51fe58ceea44d836e6c
    windows:
      amd64: sha256:d84edbf6ba856282b1c2d0685d4e2c866ba9380c53d09d768ab9fe7225bae5d2
  v1.12.1:
    darwin:
      amd64: sha256:103cf133d174e214e3ae5f0c86b8bf34b325e0f48595a7dee67c7c86df4adf1d
    linux:
      amd64: sha256:abba8834d6bce74cacf4edcdf73b30075f89545ec3ca5a0594061e6cebe13975
      arm64: sha256:fffaea3c25e8d433ee30c8383207d25d289be167d0cc8053bba08cd17cd1a73e
    windows:
      amd64: sha256:b51fd44d0e27aad6003558a573d50f85a7ffb732e827f6b39e83f758b02f7d00
  v1.12.2:
    darwin:
      amd64: sha256:72792bf322d9b3e7648670f430d2eeee2db8f42900733d60094b0943533bbb19
    linux:
      amd64: sha256:40807b5817e5a6a64a96eb219963a48f79ae96e1ee9a7f20ae9fbab2fc048ac7
      arm64: sha256:40d218cee04db06af7976a7e6c81416bca4b814a55652f0b317c8feaddf6837f
    windows:
      amd64: sha256:972333da0f888ab347da19149dd9f332a5bbe25d9d23f5ff5be087c2558bd67d
  v1.13.0:
    darwin:
      amd64: sha256:1fe57b30eb47d0c2f89ff4df6936bff2cac3a8f26f31efa3105700d192331f80
    linux:
      amd64: sha256:4314fb34e46be9b5558eea014060d8283a82074b33366e4163e5afaa69ddae23
      arm64: sha256:14d96e9ccb065bdbe2b0123731ce676de871cc9ae0406638c9a85c8809f6c435
    windows:
      amd64: sha256:04a0c40e48eca4f12e82244b8e6d850486a1018eabf0e590a6cafe44d13d05ba
  v1.13.1:
    darwin:
      amd64: sha256:ddebf621822a477ade23aeb3a00f214591e5031342f3a52403c0be8fa1696d2b
    linux:
      amd64: sha256:8668ecbf286774e5f7d9aa849f95af2940c491a258459f93c5dd3e3c836c2cb1
      arm64: sha256:341447a66e67ad17fd8b28185360c92e7225dc01355c9987f0431b50b703cb3e
    windows:
  v1.13.2:
    darwin:
      amd64: sha256:e656a8ac9272d04febf2ed29b2e8866bfdb73f55e098026384268851d7aeba74
    linux:
      amd64: sha256:2c7ab398559c7f4f91102c4a65184e0a5a3a137060c3179e9361d9c20b467181
      arm64: sha256:7b36754a3dac81166825b067fd788d5d2b75f834352b2502141809cdb20ef59a
    windows:
      amd64: sha256:86a5f0a1e9cddf28dc23f4f4beddbc7733822392a5eb946c1e73857c91d964f0
  v1.13.4:
    darwin:
      amd64: sha256:cb5dc3c36363d0192756c4cc8f56117272aaed071e5e805ca657f576c6e0f1d2
    linux:
      amd64: sha256:92de2edbc8c21cfce6f70daa48e95560274a7413a51a6f8c348d974490fd1338
      arm64: sha256:859cb1e7687c916f7f50fb3e5de84d0f0884c3cff857d764583cd2be4f676ded
    windows:
      amd64: sha256:9d728730c9b0d8356669370f818fb1cf4e50c6dbb7c65f3b015e40873a062759

kubectl_install_dir: /usr/local/bin
kubectl_privilege_escalate: True
